version: '3.6'

networks:
  api-network:

services:
  api:
    build: '.'
    container_name: '${CONTAINER_NAME}'
    ports:
      - '${PORT}:${PORT}'
    networks:
      - 'api-network'
    restart: 'always'
    environment:
      - 'NODE_ENV=production'
      - 'PORT=${PORT}'
  postgresdb:
    image: 'clkao/postgres-plv8:12-2'
    container_name: '${POSTGRES_CONTAINER_NAME}'
    ports:
      - '5432:5432'
    networks:
      - 'api-network'
    restart: 'always'
    environment:
      - 'PGDATA=/var/lib/postgresql/data'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_DB=${POSTGRES_DB}'
    volumes:
      - './postgres/init:/docker-entrypoint-initdb.d'
      - '~/data/postgresdb:/var/lib/postgresql/data'
